Dev 819 -> Staging
bolideai/tool-cs-fixer pull request #1
Opened 2022-10-13 12:47 UTC by enmaboya

2022-10-13 13:07 UTC, execut requested changes
Нет инструкции по использованию

2022-10-13 13:51 UTC, execut requested changes

2022-10-13 13:51 UTC, execut commented on README.md
> +[notion](https://www.notion.so/PHP-CS-Fixer-8e6514510f004ced96984b519d1eb0e7)
Мож ликвидируем notion и сюда лучше? В этом есть следующие преимущества:
1. Не нужно переходить никуда
2. Есть версионность
3. Невозможно потерять

2022-10-13 13:52 UTC, execut commented on README.md
> +[notion](https://www.notion.so/PHP-CS-Fixer-8e6514510f004ced96984b519d1eb0e7)
4. Есть доступ к инструкции прямо в IDE, не нужно ходить в бразер

2022-10-13 14:10 UTC, enmaboya commented on README.md
> +[notion](https://www.notion.so/PHP-CS-Fixer-8e6514510f004ced96984b519d1eb0e7)
@execut лично мне не принципиально, изначально в notion записывали, чтобы всё в одном месте было, и любой человек прочитать мог.
Хотя дока к фиксеру вряд-ли кому-то кроме нас нужна )

в общем если Юра Кравцов не против, то сделаю тут.

2022-10-13 14:28 UTC, yurikravtsov commented on README.md
> +[notion](https://www.notion.so/PHP-CS-Fixer-8e6514510f004ced96984b519d1eb0e7)
Нужно только 1 хранилище всей документации. Если вы куда-то перетащите ВСЮ свою информацию и она никогда никому другому не понадобится (поддержку например неразумно сюда затаскивать) - тогда ок.
Всю будете перетаскивать?

2022-10-13 14:40 UTC, execut commented on README.md
> +[notion](https://www.notion.so/PHP-CS-Fixer-8e6514510f004ced96984b519d1eb0e7)
Я подразумевал только информацию про cs-fixer перетащить. Одну статью, которую Виталя выше привёл. Но если информация затрагивает не только разработчиков или QA, то да, есть смысл в notion её хранить.

Думаю есть смысл потом и документацию по API подобным образом перетаскивать. Ведь она меняется от версии к версии вместе с самим приложением и всегда есть шанс забыть про notion. А тут будет всегда под рукой и будет глаз резать.

2022-10-14 12:01 UTC, enmaboya commented on README.md
> +[notion](https://www.notion.so/PHP-CS-Fixer-8e6514510f004ced96984b519d1eb0e7)
https://github.com/bolideai/tool-cs-fixer/blob/DEV-819/docs/how-to-use.md

2022-10-14 12:02 UTC, execut approved these changes

2022-10-14 12:05 UTC, merged